---
name: Checks

on: [push]

jobs:
  # test-lint is the ID may be used as a ref to run
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    # different thing runs on the job
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

#So action is the way it works, is you can actually create your own actions.
#Well, you can reuse existing actions that are used for particular jobs.
#And action is basically just a Docker container and a Docker configuration that's set up to perform
#a certain task.So this particular action is the Docker slash log in action.
# Here we define the steps in such  way, like we want to execute via system.
